name: EasyPVP
version: '1.4-DEVELOPMENT'
main: org.radarw.easypvp.EasyPVP
api-version: '1.21'
depend: [WorldGuard]
commands:
  amialive:
    description: Does something cool
    usage: /<command>
    permission: easypvp.use
    permission-message: You don’t have permission to use this command.
  arena:
  kpdebug:
    description: Does something cool
    usage: /<command>
    permission: easypvp.use
    permission-message: You don’t have permission to use this command.
  deposit:
  withdraw:
  givegold:
  sellitems:
  buy:
  shop: